disabled_rules:
#   - function_parameter_count
#   - nesting
  - line_length
  # - variable_name
  - type_name
#   - weak_delegate
#   - trailing_comma
opt_in_rules:
  - empty_count
  - force_unwrapping
  - private_outlet
  - missing_docs
# line_length:
#   warning: 300
type_body_length:
  warning: 300
  error: 400
file_length:
  warning: 500
  error: 1200
variable_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
included:
  - Source/
reporter: "xcode"
